### ISSUE TITLE
[BUG] 소셜로그인 시 동시성 이슈

### ISSUE THREAD

**Issue by dayaelee** [kakaotech-bootcamp-22/be#10]
### 🐞 버그 설명
카카오 로그인 시, 최초 로그인 시 동시성 이슈로 인해 동일한 소셜 아이디로 두 개의 회원 정보가 생성되는 문제가 발생합니다. 이로 인해 DB에 유니크 속성이 설정된 소셜 아이디 필드에서 중복 값이 입력되지 않도록 막고 있으며, 백엔드에서 해당 중복을 처리하려고 에러를 반환하고 있습니다. 구글 로그인에서는 이와 같은 문제가 발생하지 않습니다.

### 🛠 재현 방법
문제를 재현하기 위한 단계:
카카오 계정으로 로그인 시도
로그인 요청이 동시에 처리되며, 중복된 소셜 아이디가 DB에 저장됨
백엔드에서 중복 처리로 인해 에러가 반환됨

### 🖥 환경
- OS: [MacOS]
- Browser: [Chrome]
- Version: 
      - Java: 21 
      - Spring Boot: 3.3.3
      - PostgreSQL JDBC 드라이버: postgresql:42.6.0 
      - JUnit: 5 (JUnit 플랫폼 사용)
     

### 📝 추가 설명
동시성 이슈로 인해 같은 소셜 아이디가 두 번 등록되는 문제 발생. 현재는 중복 등록을 방지하기 위해 DB에서 유니크 제약을 두고 있으며, 이로 인해 에러가 발생하는 상황입니다.

**Comment by konempty** [comment]
@dayaelee 
이슈 관리는 지라를 통해서 관리하시는게 좋습니다~!
